// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cygzhipasqyudpgddgsa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN5Z3poaXBhc3F5dWRwZ2RkZ3NhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1MjE2ODAsImV4cCI6MjA2NTA5NzY4MH0.e84UmHyxnu7o-vtFJ3Ey4aHVpoFG1Kso-QouOetr7wE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);